# Generated by Django 3.2.5 on 2021-07-07 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
