# Generated by Django 3.2.5 on 2021-07-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210707_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
