# Generated by Django 3.2.5 on 2021-07-08 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_products_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
